version: "2"
run:
  concurrency: 4
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    gocyclo:
      min-complexity: 20
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: G402
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
