name: dnslookup
version: '1.3.0'
summary: Simple command-line tool to make DNS lookups using any protocol.
description: |
  Simple command-line tool to make DNS lookups to the specified server using any protocol: DNS, DOH, DOT, DNSCrypt.

  Examples:

  Plain DNS:
    `./dnslookup example.org 176.103.130.130`

  DNS-over-TLS:
    `./dnslookup example.org tls://dns.adguard.com`

  DNS-over-HTTPS:
    `./dnslookup example.org https://dns.adguard.com/dns-query`

  Machine-readable format:
    `JSON=1 ./dnslookup example.org 176.103.130.130`

confinement: strict
base: core18

parts:
  dnslookup:
    plugin: make
    source: .
    build-snaps: [ go ]
    build-packages: [ git, build-essential ]
    override-build: |
      VERSION="1.3.0-${SNAP_REVISION}" make
      cp dnslookup ${SNAPCRAFT_PART_INSTALL}/

apps:
  dnslookup:
    command: dnslookup
    plugs:
      - network
